
version: "3"

services:
  gumball:
    image: spring-cashier
    volumes:
      - /tmp:/tmp
    networks:
      - network   
    ports:
      - 9090    
    restart: always     
  lb:
    image: eeacms/haproxy
    depends_on:
    - gumball
    ports:
    - "80:5000"
    - "1936:1936"
    environment:
      BACKENDS: "cashier"
      BACKENDS_PORT: "9090"
      DNS_ENABLED: "true"
      COOKIES_ENABLED: "false"
      LOG_LEVEL: "info"
    networks:
      - network

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge
