apiVersion: v1
kind: Pod
metadata:
  name: spring-customer
  namespace: default
  labels:
    name: spring-customer
spec:
  containers:
    - image: juss2000/spring-customer
      name: spring-customer
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
readinessProbe:
  httpGet:
  path: /ping
  port: 8080

 readinessProbe:
   httpGet:
   path: /ping
   port: 8080
   
