apiVersion: v1
kind: Service
metadata:
  name: spring-customer-service 
  namespace: default
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - port: 8080
    targetPort: 8080 
    nodePort: 32000
    protocol: TCP
  selector:
    name: spring-customer
